# -*- coding: utf-8 -*-
"""직무 ① 공통 — 어느 공장·회사에서나 쓰는 말.
   근거: KOTRA 2023 「베트남 내 한국인 취업 현황」 — 한국인 취업의 **40%가 생산관리**,
   그다음이 영업·회계다. 그래서 생산관리 말이 가장 두껍다.
   선배 시험·일터 단톡방에서 나온 말과 어긋나지 않게 맞췄다."""

W = {
"공통 · 생산과 공정": [
 ("kế hoạch sản xuất","생산 계획"),("lệnh sản xuất","작업 지시서"),("đơn hàng","오더·주문"),
 ("số lượng đặt","주문 수량"),("sản lượng ngày","일 생산량"),("mục tiêu ngày","일일 목표"),
 ("đạt kế hoạch","계획 달성"),("chưa đạt","미달"),("vượt kế hoạch","계획 초과"),
 ("năng suất","생산성"),("hiệu suất","효율"),("thời gian chu kỳ","사이클 타임"),
 ("công đoạn trước","전 공정"),("công đoạn sau","후 공정"),("nút thắt cổ chai","병목 공정"),
 ("cân bằng chuyền","라인 밸런싱"),("chuyển đổi mẫu","기종 전환"),("chạy thử","시운전"),
 ("sản xuất thử","시생산"),("sản xuất hàng loạt","양산"),("dừng chuyền","라인 정지"),
 ("khởi động chuyền","라인 가동"),("tăng ca","잔업하다"),("ca ngày","주간조"),("ca đêm","야간조"),
 ("giao ca","교대 인수인계"),("bảng giao ca","인수인계 일지"),("điểm danh","출석 점검"),
 ("thao tác chuẩn","표준 작업"),("hướng dẫn công việc","작업 표준서"),("đào tạo tay nghề","기능 교육"),
 ("thợ lành nghề","숙련공"),("thợ mới","신입 작업자"),("người thay ca","교대 대체 인력"),
 ("thiếu người","인원 부족"),("bố trí nhân lực","인력 배치"),("luân chuyển","순환 배치"),
 ("cải tiến","개선"),("đề xuất cải tiến","개선 제안"),("lãng phí","낭비"),("tồn đọng","적체"),
 ("hàng dở dang","재공품"),("thành phẩm","완제품"),("bán thành phẩm","반제품"),
 ("phế phẩm","폐기품"),("hàng sửa","수리품"),("làm lại","재작업하다"),
],
"공통 · 품질과 검사": [
 ("tiêu chuẩn chất lượng","품질 기준"),("bảng kiểm","점검표"),("kiểm tra đầu chuyền","초물 검사"),
 ("kiểm tra giữa chuyền","공정 검사"),("kiểm tra cuối","최종 검사"),("kiểm toàn bộ","전수 검사"),
 ("kiểm xác suất","샘플 검사"),("mẫu đối chiếu","한도 견본"),("hàng đạt","합격품"),
 ("hàng không đạt","불합격품"),("phân loại","선별하다"),("cách ly hàng lỗi","불량품 격리"),
 ("nguyên nhân gốc","근본 원인"),("phân tích nguyên nhân","원인 분석"),("biện pháp khắc phục","시정 조치"),
 ("biện pháp phòng ngừa","예방 조치"),("tái phát","재발"),("khiếu nại khách hàng","고객 클레임"),
 ("báo cáo lỗi","불량 보고"),("phiếu kiểm tra","검사 성적서"),("dung sai cho phép","허용 공차"),
 ("đo kích thước","치수 측정"),("hiệu chuẩn thiết bị","계측기 교정"),("độ chính xác","정밀도"),
 ("ổn định chất lượng","품질 안정"),("truy tìm nguyên nhân","원인 추적"),
],
"공통 · 자재와 창고": [
 ("yêu cầu vật tư","자재 요청"),("cấp phát vật tư","자재 불출"),("trả lại kho","창고 반납"),
 ("kiểm kê định kỳ","정기 재고 조사"),("hàng tồn lâu","장기 재고"),("hết hàng","재고 소진"),
 ("đặt thêm","추가 발주"),("nhà cung cấp","공급업체"),("hàng nhập về","입고품"),
 ("kiểm tra hàng nhập","수입 검사"),("mã vật tư","자재 코드"),("số lượng thực tế","실물 수량"),
 ("chênh lệch","차이·오차"),("thất thoát","분실·손실"),("hạn dùng vật tư","자재 유효기간"),
 ("bảo quản","보관하다"),("khu vực để hàng","적치 구역"),("dán nhãn vật tư","자재 표시"),
 ("đóng gói lại","재포장"),("vật tư phụ","부자재"),
],
"공통 · 기계와 설비": [
 ("bảo trì định kỳ","정기 보전"),("bảo trì phòng ngừa","예방 보전"),("sửa chữa khẩn","긴급 수리"),
 ("nhật ký thiết bị","설비 일지"),("kiểm tra hằng ngày","일상 점검"),("bôi trơn","급유하다"),
 ("thay dầu","오일 교환"),("làm sạch máy","설비 청소"),("hiệu chỉnh máy","설비 조정"),
 ("thông số vận hành","운전 조건"),("quá tải","과부하"),("rung lắc","진동"),("tiếng ồn bất thường","이상 소음"),
 ("rò rỉ","누유·누수"),("mất điện","정전"),("khởi động lại","재기동"),("khoá an toàn","안전 잠금"),
 ("phụ tùng dự phòng","예비 부품"),("tuổi thọ thiết bị","설비 수명"),
],
"공통 · 안전과 환경": [
 ("nội quy an toàn","안전 수칙"),("huấn luyện an toàn","안전 교육"),("kiểm tra an toàn","안전 점검"),
 ("tai nạn lao động","산업 재해"),("suýt xảy ra tai nạn","아차 사고"),("sơ cứu","응급 처치"),
 ("bình chữa cháy","소화기"),("lối thoát hiểm","비상구"),("diễn tập cháy nổ","소방 훈련"),
 ("đồ bảo hộ","보호구"),("kính bảo hộ","보안경"),("nút bịt tai","귀마개"),("giày bảo hộ","안전화"),
 ("khu vực cấm","출입 금지 구역"),("biển báo","표지판"),("chất thải","폐기물"),
 ("phân loại rác","쓰레기 분리"),("tiết kiệm điện","전기 절약"),("ô nhiễm","오염"),
 ("kiểm tra sức khoẻ","건강 검진"),
],
"공통 · 사람과 조직": [
 ("hợp đồng lao động","근로 계약"),("thử việc","수습"),("chính thức","정규직 전환"),
 ("bảng lương","급여 명세서"),("lương cơ bản","기본급"),("phụ cấp","수당"),("thưởng","상여금"),
 ("lương tháng 13","13월 월급"),("bảo hiểm xã hội","사회보험"),("bảo hiểm y tế","의료보험"),
 ("nghỉ phép năm","연차 휴가"),("nghỉ ốm","병가"),("nghỉ không lương","무급 휴가"),
 ("đơn xin nghỉ","휴가 신청서"),("chấm công","근태 기록"),("đi muộn","지각"),("về sớm","조퇴"),
 ("tự ý nghỉ","무단 결근"),("kỷ luật","징계"),("khen thưởng","포상"),("đánh giá năng lực","인사 평가"),
 ("thăng chức","승진"),("chuyển bộ phận","부서 이동"),("thôi việc","퇴사"),("bàn giao","인수인계"),
 ("công đoàn","노동조합"),("đối thoại","노사 대화"),("đình công","파업"),
 ("phỏng vấn tuyển dụng","채용 면접"),("sơ yếu lý lịch","이력서"),
],
"공통 · 서류와 회계": [
 ("báo cáo hằng ngày","일일 보고"),("báo cáo tuần","주간 보고"),("báo cáo tháng","월간 보고"),
 ("biên bản họp","회의록"),("trình ký","결재 상신"),("phê duyệt","승인하다"),("từ chối duyệt","반려하다"),
 ("bản gốc","원본"),("bản sao","사본"),("công chứng","공증"),("lưu hồ sơ","서류 보관"),
 ("chi phí","비용"),("doanh thu","매출"),("lợi nhuận","이익"),("lỗ","손실"),("ngân sách","예산"),
 ("quyết toán","결산"),("hoá đơn đỏ","세금계산서"),("thuế thu nhập","소득세"),("tạm ứng","가불·선지급"),
 ("thanh toán","정산·결제"),("chuyển khoản","계좌 이체"),("báo giá","견적서"),("đàm phán giá","가격 협상"),
 ("ký hợp đồng","계약 체결"),("gia hạn hợp đồng","계약 연장"),("chấm dứt hợp đồng","계약 해지"),
],
}
