#!/usr/bin/env python3
"""빠진 낱말 그림의 **그릴 거리**를 적어 둔 표. 화풍 지시는 아래에서 자동으로 붙는다.

원칙 셋:
 1) **한국어 뜻을 그린다.** ko_days.json 의 베트남어 풀이는 군데군데 틀려 있다
    (경우→"đạo lý"=도리, 주문→"câu thần chú"=주문(呪文), 체하다→"đầy bụng"=체증,
    기관→"động cơ"=엔진, 가장→"người chủ gia đình"=가장(家長)).
    그 풀이를 그대로 그리면 **엉뚱한 그림**이 된다. 아래 표는 한국어를 보고 썼다.
 2) **추상어도 반드시 그린다.** 화살표·저울·엑스표·등호·막대그래프·손짓처럼
    이미 이 앱이 쓰던 기호 문법을 그대로 쓴다(x-khong=엑스표, x-cung=등호).
 3) **정확해야 하는 것은 여기 없다.** 색·무늬·도형은 생성 모델이 못 맞춘다 →
    tools/draw_words.py 가 직접 그린다.

실행: python3 tools/word_prompts.py   (docs/image-prompts.md 뒤에 덧붙인다)
"""
import json
import pathlib

R = pathlib.Path(__file__).resolve().parent.parent
STYLE = ("simple flat illustration, soft pastel colors, thick outlines, "
         "plain white background, no text, no letters")

# 코드로 직접 그리는 것 — 이 표에 넣지 않는다 (draw_words.py 가 맡는다)
DRAWN = {"d435-xanh-da-troi", "d435-xanh-nuoc-bien", "d435-xanh-la-cay",
         "d435-da-cam", "d435-xam", "d435-mau-sac", "d435-hoa-van",
         "d435-ke-soc", "d435-trong-suot", "d435-hinh-tron"}

SUBJ = {
    # ── 초급1 · 사람과 사물 ──────────────────────────────────
    "k-gukjeok": "a passport next to a globe",
    "k-seonsaengnim": "a teacher standing beside a blackboard, pointing",
    "k-hoesawon": "an office worker in a suit holding a briefcase",
    "k-haksaeng": "a student with a backpack holding a notebook",
    "k-chimdae": "a bed with a pillow and folded blanket",
    "k-hyudae-jeonhwa": "a smartphone held in one hand",
    "k-sigye": "a round wall clock",
    "k-hakgyo": "a school building with a flag pole and a wide entrance",
    "k-gyosil": "a classroom with rows of desks facing a blackboard",
    "k-chaek": "an open book",
    "k-keuda": "a big elephant standing beside a tiny mouse, elephant emphasized",
    "k-jakda": "a tiny mouse standing beside a big elephant, mouse emphasized",
    "k-mianhada": "a person bowing slightly with an apologetic expression, hand on chest",
    "k-gayo": "a microphone with music notes floating around it",
    "k-geuraeseo": "two boxes joined by a thick arrow pointing from cause to result",
    "k-uri": "a group of people standing together in a circle, arms around shoulders",
    "k-eumak": "music notes and a pair of headphones",
    "k-ttaemun": "a falling domino knocking over the next one",
    "k-geureona": "two arrows turning away from each other in opposite directions",
    "k-pyeonuijeom": "a small convenience store front at night with bright windows",
    "k-sikdang": "a restaurant table set with dishes and chairs",
    "k-kape": "a coffee cup on a saucer beside a small cafe table",
    "k-gongwon": "a park with a bench, a tree and a walking path",
    "k-gimchijjigae": "a bubbling red stew in a black stone pot",
    "k-bibimbap": "a bowl of rice topped with colorful vegetables arranged in sections",
    "k-bulgogi": "thin marinated beef slices grilling on a domed pan",
    "k-samgyeopsal": "thick strips of pork belly grilling on a griddle",
    "k-ramyeon": "a pot of instant noodles with a lid and chopsticks",
    "k-gimbap": "sliced seaweed rice rolls arranged on a plate",
    "k-banchan": "several small side dishes in little bowls around a table",
    "k-jeotgarak": "a pair of chopsticks resting on a chopstick rest",
    "k-gangaji": "a small puppy sitting and wagging its tail",
    "k-japji": "a glossy magazine lying open",
    "k-noteubuk": "an open laptop computer",
    "k-nokcha": "a cup of green tea with tea leaves beside it",
    "k-cheongsogi": "an upright vacuum cleaner",
    "k-gyeran": "two chicken eggs, one whole and one cracked into a bowl",
    "k-syopinghada": "a person pushing a shopping cart with bags inside",
    "k-baekhwajeom": "a tall department store building with big display windows",
    "k-jinandal": "a wall calendar with the previous month's page flipped back",
    "k-isa": "a moving truck with cardboard boxes being carried into a house",
    "k-yeonghwa": "a movie screen with two cinema seats and a film reel",
    "k-doeda": "a caterpillar transforming into a butterfly with an arrow between",
    "k-chulgeun": "a person in work clothes leaving home in the morning, sun rising",
    "k-toegeun": "a person leaving an office building in the evening, sun setting",
    "k-geureotda": "a person nodding with a checkmark in a speech bubble",
    "k-jalhada": "a person giving a thumbs up beside a high score board",
    "k-mothada": "a person shrugging with an X mark in a speech bubble",
    "k-halmeoni": "a kind elderly woman with grey hair, smiling",
    "k-halabeoji": "a kind elderly man with grey hair, smiling",
    "k-bumonim": "a mother and father standing side by side",
    "k-chodaejang": "an invitation card in an envelope with a ribbon",
    "k-keikeu": "a layered birthday cake with candles",
    "k-gyeolhonsik": "a bride and groom under a wedding arch",
    "k-joleopsik": "a graduate in cap and gown holding a diploma",
    "k-eobeoinal": "a child giving a red carnation flower to parents",
    "k-hyuga": "a beach chair with a parasol and a suitcase",
    "k-chincheok": "a family tree chart with several relatives' portraits",
    "k-hwajangpum": "cosmetic bottles, a lipstick and a cream jar on a shelf",
    "k-hyuil": "a calendar page with one day circled in red and a hammock",

    # ── 초급2 · 이동과 생활 ─────────────────────────────────
    "k-geogi": "a person pointing at a spot far away with a location pin there",
    "k-jadongcha": "a small car seen from the side",
    "k-jajeongeo": "a bicycle seen from the side",
    "k-jihacheol": "a subway train arriving at an underground platform",
    "k-gicha": "a train travelling on rails through countryside",
    "k-himdeulda": "a person straining to push a heavy boulder, sweat drops",
    "k-gajang": "three podium blocks with a trophy on the tallest one",
    "k-jeil": "a first place ribbon with the number one shape as a shining star",
    "k-saenggakhada": "a person with a thought bubble containing gears",
    "k-moreuda": "a person with an empty question mark thought bubble, palms up",
    "k-mandeulda": "hands shaping clay into a pot on a workbench with tools",
    "k-eotteon": "a row of identical boxes with one marked by a question mark",
    "k-dapjanghada": "an envelope flying back with a reply arrow curving to sender",
    "k-sigan": "an hourglass beside a clock face",
    "k-jangso": "a map with a location pin planted on it",
    "k-hanjan": "two glasses clinking together in a toast",
    "k-nalssi": "a sky showing sun, cloud and rain drops side by side",
    "k-bom": "cherry blossom branches with new green sprouts",
    "k-yeoreum": "a bright sun over a beach with an ice cream cone",
    "k-gaeul": "falling red and yellow maple leaves",
    "k-gyeoul": "a snowman with falling snowflakes",
    "k-ttatteuthada": "a person warming hands on a steaming mug, soft sun glow",
    "k-malda": "a clear blue sky with a bright sun and no clouds",
    "k-heurida": "a sky fully covered by thick grey clouds",
    "k-eopda": "an empty open box with a dashed outline where an object was",
    "k-gwi": "a human ear seen from the side, sound waves beside it",
    "k-mok": "a neck and shoulders outline with the neck highlighted",
    "k-pal": "a bare human arm bent at the elbow",
    "k-mureup": "a bent leg with the knee joint highlighted",
    "k-bal": "a bare human foot seen from the side",
    "k-juchajang": "a parking lot with painted lines and a few parked cars",
    "k-juchahada": "a car backing into a marked parking space",
    "k-bakmulgwan": "a museum building with tall columns and a display vase",
    "k-gyeongchalseo": "a police station building with a blue lamp at the door",
    "k-dongmulwon": "a zoo entrance gate with a giraffe and an elephant behind",
    "k-kaemping": "a tent beside a campfire under trees",
    "k-joleophada": "a graduate tossing a graduation cap into the air",
    "k-iphakhada": "a child with a backpack walking through a school gate",
    "k-jeomsimsigan": "a clock at noon beside a lunch tray",
    "k-uisikju": "three icons side by side, clothing, a bowl of food, a house",
    "k-pyeongil": "a calendar week with the five weekdays shaded",
    "k-gyotong-kadeu": "a transit card being tapped on a bus card reader",
    "k-patbingsu": "a tall bowl of shaved ice topped with red bean and fruit",
    "k-joyonghada": "a person holding one finger to their lips, quiet room",
    "k-sikkeureopda": "a person covering their ears, loud jagged sound lines around",
    "k-neolda": "a wide open empty room with arrows pushing the walls outward",
    "k-jopda": "a narrow corridor with walls close on both sides",
    "k-gabang": "a shoulder bag with a zipper and a strap",
    "k-haru": "a sun and a moon on a single arc from sunrise to night",
    "k-daehada": "two people sitting face to face across a small table",
    "k-wihada": "a person holding a gift out toward another person, heart above",
    "k-sahoe": "many small human figures connected by lines into a network",
    "k-olgida": "a person lifting a box and setting it down in a new place, arrow",
    "k-ittaga": "a clock with an arrow sweeping a short way forward",
    "k-jeonhwa": "a telephone handset with sound waves",
    "k-geureon": "a hand pointing at a distant object with a dotted line",
    "k-gyeongu": "a path splitting into three branches, each with a different sign",
    "k-sinda": "a person pulling a shoe onto their foot",
    "k-hanbeon": "a single tally mark on a slate with one finger raised",
    "k-eumsik": "a plate with rice, soup and side dishes",
    "k-norae": "a person singing into a microphone, music notes",
    "k-jasin": "a person looking at their own reflection in a mirror, confident",
    "k-saenggak": "a head silhouette with a lightbulb inside",
    "k-tonghada": "a tunnel with a road passing straight through a hill",
    "k-sori": "concentric sound wave rings spreading from a small speaker",
    "k-ireon": "a hand pointing at a nearby object with a short dotted line",
    "k-yeoja": "a woman standing, simple portrait",
    "k-jeongdo": "a measuring gauge with a needle pointing partway along a scale",
    "k-gimchi": "a bowl of red napa cabbage kimchi",
    "k-boida": "an eye with light rays coming from an object toward it",
    "k-gajida": "a person holding an object close with both hands",
    "k-bi": "raindrops falling from a cloud onto an umbrella",
    "k-gajyeooda": "a person carrying a box toward the viewer, forward arrow",
    "k-ai": "a small child standing and smiling",
    "k-jinada": "a figure walking past a signpost, arrow continuing beyond",
    "k-ingan": "a human figure silhouette standing alone, simple and dignified",
    "k-sasil": "a magnifying glass over a document with a checkmark",
    "k-nada": "a green sprout pushing up out of soil",
    "k-oeropda": "a single person sitting alone on a bench in a wide empty space",
    "k-telrebijeon": "a television set on a stand",
    "k-gibun": "a face with a smile and a face with a frown side by side",
    "k-ireotda": "a hand presenting a nearby object on an open palm",
    "k-uihada": "an arrow leaning on a solid pillar for support",
    "k-sidae": "a long horizontal timeline with era markers along it",
    "k-ireohada": "a hand gesturing toward a nearby scene, dotted outline",
    "k-jam": "a person sleeping in bed with Z shapes floating",
    "k-jagi": "a person pointing at their own chest with a thumb",
    "k-segye": "a globe of the earth with continents",
    "k-daetongryeong": "a speaker at a podium with a national emblem and flags behind",
    "k-gaji": "three different objects lined up, each in its own bracket",
    "k-eolgul": "a simple human face, front view",
    "k-maeil": "a calendar with a check mark in every single square",
    "k-gongbu": "a student at a desk reading with a pencil and open books",
    "k-yaksok": "two hands linking little fingers, a calendar behind",
    "k-undonghada": "a person jogging in sportswear",
    "k-olhae": "a calendar showing a whole year with the current year highlighted",
    "k-kkeungida": "a rope snapped in two with the broken ends apart",
    "k-geugeo": "a hand pointing at one object among several, that one glowing",
    "k-gukga": "a map outline with a flag planted at its center",
    "k-geureonde": "a straight road with a sudden fork turning aside",
    "k-yori": "hands cooking at a stove with a frying pan and vegetables",
    "k-gareuchida": "a teacher pointing at a board while a student watches",
    "k-chinjeol": "a person helping an elderly person carry a bag, warm smile",
    "k-yeoseong": "an adult woman standing, professional and calm",
    "k-maeum": "a heart shape inside a chest outline with soft glow",
    "k-geuncheo": "a house with a small circle drawn around the nearby area",
    "k-gwangye": "two circles overlapping with a line connecting their centers",
    "k-namja": "an adult man standing, simple portrait",
    "k-natanada": "a figure stepping out from behind a curtain into light",
    "k-jiyeok": "a map with one region shaded and outlined",
    "k-cheongso": "hands sweeping with a broom and a dustpan",
    "k-iyagi": "two people talking with a large speech bubble between them",
    "k-moseup": "a person's silhouette outline seen clearly against light",
    "k-naeda": "a hand pushing a document out through a window slot",
    "k-eopi": "an empty hand with a crossed out object beside it",
    "k-ibeon": "a calendar with the current week circled, arrow pointing at it",
    "k-saenghwal": "a day in a home, cooking, cleaning and resting shown in one scene",
    "k-seonggyeok": "three faces showing calm, cheerful and stubborn expressions",
    "k-sai": "two objects with a measured gap and arrows between them",
    "k-urinara": "a country map with a flag and small houses on it",
    "k-anda": "a person sitting down on a chair",
    "k-cheoeum": "a starting line with a runner at the very first step",
    "k-geuttae": "a clock with a marked point in the past, arrow pointing back",
    "k-gatda": "a person carrying an object in their hands, holding it close",
    "k-teukhi": "a row of identical shapes with one highlighted by a spotlight",
    "k-naenyeon": "a calendar page turning forward to the next year",
    "k-yeolsimhi": "a person studying hard with sweat drops and a burning focus",
    "k-moeuda": "hands gathering scattered coins into one pile",
    "k-isang": "a bar rising above a marked threshold line, arrow pointing up",
    "k-gyoyuk": "a teacher, a book and a graduation cap arranged together",
    "k-gyeongje": "coins, a rising graph line and a shopping bag together",
    "k-oegukin": "a traveler with a passport and a suitcase at an airport",
    "k-deungrokjeung": "an identification card with a photo and a chip",
    "k-unjeon": "hands on a steering wheel seen from the driver's seat",
    "k-japda": "a hand gripping a handle firmly",
    "k-yesul": "a painter's palette, a brush and a framed canvas",
    "k-gomapda": "a person bowing with hands together, warm grateful expression",
    "k-yeoksa": "an old scroll, a ruin column and an hourglass together",
    "k-ilda": "a person reading a book with eyes following the lines",
    "k-gyeolgwa": "a finish line with a scoreboard showing a final total",
    "k-naeyong": "an open box showing the items packed inside it",
    "k-mulron": "a person nodding firmly with a large checkmark beside",
    "k-dangsin": "a hand pointing forward at the viewer politely",
    "k-neotda": "a hand dropping a coin into a slot in a box",
    "k-neukkida": "a hand touching a surface with small sensation lines",
    "k-maepda": "a red chili pepper with flames and a sweating face",
    "k-dambae": "a single cigarette with a thin curl of smoke",
    "k-piuda": "a flower bud opening into a full bloom, arrow between",
    "k-uimi": "a word card with an arrow pointing to a picture of its meaning",
    "k-balhida": "a lantern lighting up a dark corner, beam of light",
    "k-jukda": "a wilted flower drooping beside a fallen petal",
    "k-seuda": "a fallen post being raised upright by hands, arrow upward",
    "k-jucha": "a car parked inside painted parking lines",
    "k-changmun": "an open window with curtains and daylight outside",
    "k-jeongchi": "a podium with a microphone, a ballot box beside it",
    "k-gukmin": "a crowd of people standing together beneath a flag",
    "k-yaegi": "two friends chatting casually with speech bubbles",
    "k-yeongu": "a microscope, a notebook and test tubes on a lab bench",
    "k-jumun": "a customer pointing at a menu while a waiter writes",
    "k-ttohan": "two identical items with a plus sign added beside them",
    "k-ttoneun": "a path forking into two, with a choice mark at the fork",
    "k-saenggida": "a small sprout appearing where nothing was, sparkle above",
    "k-sayonghada": "a hand using a tool to do a task",
    "k-deuleooda": "a figure stepping in through an open doorway, inward arrow",
    "k-barada": "a person with hands clasped looking up at a shooting star",
    "k-neulda": "a short bar growing into a longer bar, arrow showing growth",
    "k-sesang": "a globe surrounded by small houses and people",
    "k-daehak": "a university building with columns and a graduation cap",
    "k-gaunde": "a row of five circles with the middle one highlighted",
    "k-ihu": "a timeline with a marked point and the part after it shaded",
    "k-deungsan": "a hiker with a backpack climbing a mountain trail",
    "k-eottae": "a person tilting their head with a question mark, palms open",
    "k-baeu": "an actor on a stage under a spotlight with theater masks",
    "k-munhak": "a stack of novels with a quill pen resting on top",
    "k-nopda": "a tall tower next to a short one, upward arrow along the tall one",
    "k-choegeun": "a calendar with the last few days marked, arrow to today",
    "k-hwangyeong": "a green earth with trees, clean water and a leaf",
    "k-jeonhada": "a hand passing a letter into another waiting hand",
    "k-malsseum": "an elder speaking with a respectful speech bubble",
    "k-jisi": "a supervisor pointing while a worker looks in that direction",
    "k-yojeum": "a calendar with the recent days shaded and a clock beside",
    "k-gyeolhon": "two wedding rings side by side with a bouquet",
    "k-jache": "an object with a circle drawn tightly around only itself",
    "k-hwaksilhada": "a large firm checkmark stamped on a document",
    "k-bubun": "a pie chart with one slice pulled out from the whole",
    "k-byeonhwa": "a shape morphing into a different shape with an arrow between",
    "k-gwanhada": "two circles joined by a bracket linking them together",
    "k-geunyang": "a person standing still with relaxed shoulders, hands in pockets",
    "k-iyonghada": "a person tapping a card to use a machine",
    "k-geoui": "a jar filled almost to the very top, small gap left",
    "k-siheom": "a desk with an exam paper, a pencil and a clock",
    "k-mokjeok": "an arrow hitting the center of a target",
    "k-areubaiteu": "a young person working part time behind a shop counter",
    "k-sijak": "a starting pistol and a starting line with a runner crouched",
    "k-hapgyeokhada": "a person cheering while holding a paper with a pass stamp",
    "k-jungsim": "concentric circles with a bold dot at the very center",
    "k-hwaldong": "several people doing different activities in one lively scene",
    "k-murihada": "a person lifting far too many boxes, wobbling, strain lines",
    "k-dahaeng": "a person wiping their brow in relief beside an avoided pitfall",
    "k-siwonhada": "a person drinking cold water with a refreshed expression, cool air",
    "k-gwansim": "an eye looking closely at an object with a magnifying glass",
    "k-yeoksi": "a person nodding knowingly with a checkmark, as expected",
    "k-gwanggo": "a billboard with a bright frame and a megaphone beside it",
    "k-jeongsin": "a head silhouette with a bright glowing core inside",
    "k-iruda": "hands placing the final block on top of a finished tower",
    "k-daesin": "one object being swapped for another, two curving arrows",
    "k-daesinhada": "a person stepping into another person's place, swap arrows",
    "k-cheongsohada": "a person mopping a floor with a bucket beside",
    "k-gisul": "gears, a wrench and a circuit board together",
    "k-jeonche": "a full pie chart shown complete with a circle around it",
    "k-eotda": "an open hand receiving an object being placed into it",
    "k-minjok": "a group of people in traditional dress standing together",
    "k-josa": "a magnifying glass over a clipboard with a survey checklist",
    "k-gap": "a price tag hanging from an object",
    "k-geudaero": "an object and its exact copy side by side, equals sign between",
    "k-nyeondae": "a timeline divided into decade blocks",
    "k-gwahak": "a beaker, an atom symbol and a microscope together",
    "k-jayeon": "a forest with a mountain, a river and birds",
    "k-gyeolguk": "a winding path ending at a final flag",
    "k-irueojida": "scattered pieces coming together into a finished shape",
    "k-geolrida": "a coat hooked and hanging on a peg, caught",
    "k-baraboda": "a person gazing into the distance, hand shading their eyes",
    "k-daebubun": "a pie chart with a large majority slice shaded",
    "k-pyojeong": "four faces showing happy, sad, angry and surprised",
    "k-ilbu": "a pie chart with one small slice shaded",
    "k-neukkim": "a hand touching a surface with a heart and sensation lines",
    "k-naseoda": "a person stepping forward out of a line of people",
    "k-yangpa": "a whole onion with papery skin beside a cut half",
    "k-gogi": "a raw cut of meat on a wooden board",
    "k-yeonrak": "a phone with a message bubble and a signal arc",
    "k-gogae": "a person tilting their head and neck forward in a nod",
    "k-segi": "a long timeline marked into hundred year blocks",
    "k-hyeonjae": "a timeline with a bright marker on the present point",
    "k-dalrajida": "the same object shown before and after, clearly changed",
    "k-sogae": "one person introducing two others to each other with a gesture",
    "k-danida": "a person walking back and forth between home and a building",
    "k-yeonseup": "a person repeating a task with repeat arrows around them",
    "k-baljeon": "a small seedling growing into a tall tree, upward stages",
    "k-hyanghada": "a compass needle and a person facing the same direction",
    "k-gwanryeon": "two boxes joined by a chain link",
    "k-bunwigi": "a cozy room with warm light and people relaxed, soft mood",
    "k-geureohada": "a hand gesturing at a distant scene, dotted line to it",
    "k-junbihada": "a person packing a bag with items laid out ready",
    "k-yeonjang": "a bar being extended longer with an arrow at its end",
    "k-pilyo": "a hand reaching for a needed item with an exclamation mark",
    "k-kkujunhi": "footprints in an even steady line across the ground",
    "k-mitda": "two hands shaking firmly with a heart above",
    "k-natda": "a mother holding a newborn baby",
    "k-jeongbo": "a document, a folder and data lines flowing into a screen",
    "k-banmyeon": "two arrows pointing in exactly opposite directions",
    "k-himdeuleohada": "a person slumped with a heavy weight on their shoulders",
    "k-dongne": "a small neighborhood of houses along a lane with a shop",
    "k-gyotong": "a street with cars, a bus and a traffic light",
    "k-bulpyeon": "a person frowning at a broken chair with a jagged mark",
    "k-hwalbalhada": "a lively person moving energetically with motion lines",
    "k-yeokhal": "an actor's mask beside a name badge and a job tool",
    "k-haengdong": "a person striding forward taking a decisive action",
    "k-guknae": "a country map with everything inside its border shaded",
    "k-geuripda": "a person looking at a photograph with a longing expression",
    "k-eorida": "a very young child holding a toy",
    "k-gwaja": "cookies and a bag of snacks",
    "k-jaknyeon": "a calendar page for the previous year lying behind this year's",
    "k-gipda": "a cross section of deep water with the bottom far below",
    "k-moyang": "a circle, a triangle and a square lined up",
    "k-jogeon": "a checklist with boxes that must be ticked before a gate opens",
    "k-neomda": "a person stepping over a low fence, arc arrow above it",
    "k-pyeonji": "a handwritten letter beside an open envelope",
    "k-maeul": "a small village of houses among fields and a stream",
    "k-daepyo": "one figure standing in front of a group, pointed out",
    "k-ganeungseong": "a branching path with several possible routes, one glowing",
    "k-banghyang": "a compass rose with an arrow pointing one way",
    "k-daehoe": "a stadium with competitors and a trophy on a podium",
    "k-moksori": "a mouth with sound waves coming out of it",
    "k-gwail": "an apple, a banana and grapes together",
    "k-mom": "a full human body outline standing",
    "k-yeongeo": "an open English alphabet chart with letter blocks",
    "k-teunteunhada": "a strong person flexing an arm beside a solid brick pillar",
    "k-umjikida": "an object shifting position with motion lines and an arrow",
    "k-noryeok": "a person pushing a heavy rock uphill with determination",
    "k-jeonhyeo": "a completely empty container with a large X mark",
    "k-danche": "many people grouped inside one large circle",
    "k-makhida": "a pipe blocked by an obstruction, flow stopped",
    "k-geokjeong": "a person biting their lip with a worried cloud above their head",
    "k-gili": "a ruler measuring a bar from end to end with arrows",
    "k-chulbal": "a train leaving a platform, departure arrow forward",
    "k-alryeojida": "a megaphone spreading waves to many small listening figures",
    "k-ganeunghada": "a door standing open with a green checkmark beside it",
    "k-neungryeok": "a flexed arm beside a rising skill meter",
    "k-jujanghada": "a person raising a hand and speaking firmly with a bold bubble",
    "k-dolrida": "a wheel turning with circular rotation arrows",
    "k-saeop": "a handshake over a desk with a chart and a briefcase",
    "k-jinanhae": "last year's calendar page falling away behind this year's",
    "k-pyohyeon": "a person gesturing while a picture forms in a speech bubble",
    "k-jeolda": "a young person standing energetically, fresh and upright",
    "k-dongsi": "two clocks showing exactly the same time side by side",
    "k-sungan": "a camera shutter freezing a single instant, flash burst",
    "k-jeonjaeng": "a broken wall and a helmet on a scorched field, sombre",
    "k-jeokeunghada": "a plant reshaping itself to fit a new pot",
    "k-jeokeung": "a key being reshaped to fit a different lock",
    "k-silryeok": "a filled skill meter beside a person standing confidently",
    "k-jeomjeom": "a series of bars each slightly taller than the last",
    "k-geunyeo": "a woman seen from behind being pointed at from a distance",
    "k-geureoda": "a person doing an action while a dotted arrow shows the result",
    "k-jeongbu": "a government building with columns and a flag",
    "k-gwajeong": "a row of stepping stones from a start point to an end point",
    "k-saengmyeong": "a small sprout cupped in two protecting hands",
    "k-mulga": "price tags rising along an upward graph line above a shopping cart",
    "k-jeochuk": "coins dropping into a piggy bank",
    "k-julida": "a tall bar shrinking to a shorter bar with a downward arrow",
    "k-suip": "money flowing into a wallet with an inward arrow",
    "k-sageon": "a marked spot with tape and a magnifying glass over it",
    "k-jakpum": "a framed painting on a gallery wall with a small plaque",
    "k-sanghwang": "a person standing on a map looking at what surrounds them",
    "k-ttaraseo": "footprints following a dotted trail that leads to a result",
    "k-sangtae": "a gauge dial showing a needle at a certain level",
    "k-sikida": "one person pointing an order while another begins the task",
    "k-yuhak": "a student with a suitcase and a passport before a foreign campus",
    "k-dangsi": "a clock with a marker set back in the past, sepia tone",
    "k-deouk": "a bar growing even taller with a double upward arrow",
    "k-hyeonsil": "a person stepping out of a dream cloud onto solid ground",
    "k-gieop": "an office tower with a company sign and workers entering",
    "k-seongeo": "a hand dropping a ballot into a ballot box",
    "k-hyeonsang": "a magnifying glass over a curious repeating pattern in nature",
    "k-deuthada": "a hazy outline of an object with a question mark, uncertain",
    "k-silsu": "a spilled cup with a person clapping a hand to their forehead",
    "k-silsuhada": "a person knocking over a glass by accident, surprised",
    "k-maryeon": "a table set with everything laid out ready in advance",
    "k-maryeonhada": "hands laying out tools and supplies neatly before a task",
    "k-gujo": "a building's steel frame skeleton showing its structure",
    "k-ohiryeo": "an arrow bending back the opposite way from expected",
    "k-uisik": "a head silhouette with an open eye glowing inside it",
    "k-saneop": "a factory with smokestacks, gears and shipping crates",
    "k-hyeongtae": "the same volume shown as a cube, a sphere and a pyramid",
    "k-jakeop": "workers at a workbench doing a task with tools",
    "k-bihada": "two objects on a balance scale being compared",
    "k-gigwan": "an institutional building with a formal sign board",
    "k-ipjang": "a person standing firmly on one side of a line, arms crossed",
    "k-manhada": "a thumbs up beside an object marked as worthwhile",
    "k-bangsik": "three different tools each doing the same job, arranged in a row",
    "k-yeonghyang": "a stone dropped in water sending ripples outward to objects",
    "k-haengsa": "a stage with banners, an audience and a ribbon cutting",
    "k-chwisohada": "a hand crossing out a booking on a calendar with a red X",
    "k-annae": "a guide pointing the way beside an information sign",
    "k-chwiso": "a ticket stamped with a large red cancellation X",
    "k-bujakyong": "a pill bottle with an unexpected side arrow and a warning mark",
    "k-sincheong": "a hand submitting an application form at a counter",
    "k-dangye": "a staircase of steps each numbered by height",
    "k-olrida": "hands lifting a box onto a high shelf, upward arrow",
    "k-chehada": "a person pretending to read while peeking over the book",
    "k-geureotge": "a hand demonstrating a way of doing something, dotted motion",
    "k-muri": "a person carrying far more than they can, buckling under it",
    "k-nungil": "an eye with a beam of attention aimed at a distant object",
    "k-neomeojida": "a person tripping and falling forward, motion lines",
    "k-gyosa": "a teacher with a pointer standing beside a whiteboard",
    "k-jinida": "a person keeping a small treasured object in their pocket",
    "k-uiwon": "a legislator at a parliament seat with a microphone",
    "k-jumin": "residents standing together in front of their apartment block",
    "k-gyuchik": "a rulebook open beside a whistle and a signpost",
    "k-jonjae": "a solid figure standing with a soft glow marking it as present",
    "k-bunya": "a field divided into labeled plots, each with a different tool",
    "k-haengwi": "a hand carrying out a deliberate action, motion arrow",
    "k-sujun": "a horizontal level line across a scale with a marker on it",
    "k-bangsong": "a broadcast tower sending waves to a television set",
    "k-yeongeuk": "actors performing on a stage with curtains and footlights",
    "k-machangaji": "two identical objects with an equals sign between them",
    "k-seolmyeonghada": "a person pointing at a diagram while explaining to a listener",
    "k-gapjagi": "a sudden burst mark appearing with a startled figure",
    "k-gachi": "a gem on a balance scale outweighing coins",
    "k-jipdan": "a tight cluster of many identical figures grouped together",
    "k-hyeondae": "a modern city skyline with glass towers",
    "k-salpyeoboda": "a person carefully examining an object with a magnifying glass",
    "k-janggwan": "an official at a government desk with a nameplate and flag",
    "k-chai": "two bars of different heights with the gap marked between them",
    "k-pulda": "hands untying a knot in a rope",
    "k-sijeol": "an old photo album open to a page of younger days",
    "k-gosaenghada": "a person trudging through hardship with a heavy load, weary",
    "k-jaju": "a calendar with many days marked by repeated checkmarks",
    "k-jikjeop": "one hand handing an object straight to another hand, no middle",
    "k-gaein": "one single figure standing apart from a group",
    "k-geunde": "a straight arrow with a small hook turning aside",
    "k-jakga": "a writer at a desk with a pen and stacked manuscript pages",
    "k-hyogwa": "a before and after pair with a bright arrow showing improvement",
    "k-bulgyo": "a seated buddha statue with a lotus flower",
    "k-kkeulda": "a person pulling a heavy cart by a rope, drag lines behind",
    "k-daero": "a template shape and a copy made exactly to match it",
    "k-seoro": "two people facing each other, arrows pointing both ways",
    "k-daehwa": "two people talking with two speech bubbles overlapping",
    "k-ohae": "two people with mismatched thought bubbles and a tangled line",
    "k-uju": "planets and stars in dark space with a comet",
    "k-machi": "an object beside its look alike with a wavy similarity mark",
    "k-saengsan": "a factory conveyor belt producing finished goods",
    "k-ganghada": "a strong arm bending a thick metal bar",
    "k-hangye": "a bar stopping firmly at a marked red limit line",
    "k-choego": "a trophy at the very top of a podium with a crown",
    "k-natanaeda": "a hand pulling back a cloth to reveal the object beneath",
    "k-dayanghada": "many different shapes and objects arranged in variety",
    "k-nongmin": "a farmer with a hoe standing in a rice field",
    "k-deureonada": "an object emerging from behind a lifting fog",
    "k-soseol": "a thick novel open with a bookmark ribbon",
    "k-jilseo": "objects arranged in a neat orderly row, all aligned",
    "k-damda": "hands placing fruit into a basket",
    "k-naeji": "a range shown on a number line with brackets at both ends",
    "k-moida": "many small figures converging toward one central point",
    "k-simin": "citizens walking together on a city street",
    "k-hoejang": "a chairperson at the head of a meeting table",
    "k-seuseuro": "a person doing a task alone with no help, self reliant",
    "k-inal": "a calendar with one specific day circled and marked",
    "k-jedaero": "a task done neatly and correctly with a checkmark beside",
    "k-deonjida": "a person throwing a ball, arc trajectory line",
    "k-gonggan": "an empty room shown with depth arrows measuring its space",
    "k-beolida": "a person setting out tools and starting a project spread wide",
    "k-jase": "a figure shown sitting upright with good posture, guide lines",
    "k-gangjohada": "a word underlined boldly with an exclamation mark",
    "k-matda": "a person accepting a folder handed to them, taking responsibility",
    "k-hanpyeon": "a scene split in two halves showing two things at once",
    "k-gija": "a reporter with a notepad and a microphone",
    "k-juro": "a pie chart with the dominant slice clearly the largest",
    "k-hwolssin": "one bar towering far above a much shorter bar",
    "k-charari": "a balance scale tipping clearly toward the better of two options",
    "k-bokjaphada": "a tangle of many crossing lines and knots",
    "k-tongil": "two separated pieces joining into one whole",
    "k-deuleoseoda": "a person stepping across a threshold into a building",
    "k-siseol": "a public facility building with benches and equipment outside",
    "k-jubyeon": "a central object with a dotted circle of items around it",
    "k-wonin": "an arrow pointing back from a result to its starting cause",
    "k-charye": "people standing in a numbered queue one after another",
    "k-seonggonghada": "a person raising both arms at a mountain summit with a flag",
    "k-sosik": "a newspaper and a message arriving with a notification mark",
    "k-jaesan": "a house, a car and stacked coins together",
    "k-yakgan": "a measuring cup filled only a small amount at the bottom",
    "k-eoneo": "speech bubbles with different scripts and a globe behind",
    "k-yoguhada": "a person holding out a hand firmly asking, with a document",
    "k-gamdok": "a supervisor with a clipboard watching work being done",
    "k-samda": "an object being picked up and set as a marker on a base",
    "k-gigan": "a calendar with a span of days bracketed from start to end",

    # ── 베트남어 과정에서 빠져 있던 자리 ────────────────────
    "d1-a": "a person bowing politely with a small heart, respectful gesture",
    "d2-la": "an equals sign between a photo of a person and a name badge",
    "d2-cua": "a hand holding a key with an ownership tag attached",
    "d6-nhe": "a person waving goodbye softly with a gentle smile",
    "d85-gang-tay": "a pair of gloves",
    "d27-phai": "an exclamation mark beside a checklist item that must be done",
    "d75-a": "a person with a raised eyebrow and a small lightbulb, realizing",
    "d75-u": "a casual person nodding with a relaxed shrug",
    "d75-nhi": "two people nodding at each other in agreement",
    "d104-tuoi": "a crisp fresh apple with dew drops and a bright green leaf",
    "d425-ban-do": "a folded paper map spread open",
    "d425-den-giao-thong": "a traffic light with red, yellow and green lamps",
    "d425-con-hem": "a narrow alley between two close houses",
    "d59-cuoc-hen": "a formal appointment written in a diary with a pen",
    "d59-chuyen": "a departure board with one flight row highlighted",
    "d84-nho-co": "a person standing on a helping hand that lifts them up",
}


def main():
    plan = json.loads((R / "data" / "_word_img_plan.json").read_text())
    doc = R / "docs" / "image-prompts.md"
    text = doc.read_text()
    lines, miss, dup = [], [], 0
    lines.append("\n## 낱말마다 한 장 — 채워 넣은 자리\n")
    lines.append("한 챕터는 낱말 열 개다. 그림도 열 장이어야 한다. "
                 "아래는 비어 있던 자리를 채우려고 새로 적은 것이다.\n")
    seen = None
    for x in plan["new"]:
        n = x["name"]
        if n in DRAWN:
            continue                      # 코드로 그린다
        s = SUBJ.get(n)
        if not s:
            miss.append((n, x["ko"]))
            continue
        if f"**{n}.webp**" in text:
            dup += 1
            continue
        key = (x["course"], x["day"])
        if key != seen:
            seen = key
            t = x.get("theme")
            t = t.get("ko") if isinstance(t, dict) else t
            lines.append(f"\n### {'한국어' if x['course'] == 'ko' else '베트남어'} "
                         f"Day {x['day']} — {t}\n")
        lines.append(f"**{n}.webp** · {x['ko']} ({x['vi'][:40]})")
        lines.append(f"> {s}, {STYLE}\n")

    if miss:
        print(f"⚠ 그릴 거리가 빠진 낱말 {len(miss)}개: {miss[:12]}")
    doc.write_text(text + "\n".join(lines))
    print(f"프롬프트 {len(SUBJ) - dup}줄 넣음 (이미 있던 것 {dup} · 코드작화 {len(DRAWN)})")


if __name__ == "__main__":
    main()
